export const ActionTypes = {
  SET_CATEGORY: "SET_CATEGORY",
  SELECTED_CATEGORY: "SELECTED_CATEGORY",
  SET_BLOG: "SET_BLOG",
  SELECTED_BLOG: "SELECTED_BLOG",
  SET_RESULT: "SET_RESULT",
  SELECTED_RESULT: "SELECTED_RESULT",
};
